### ISSUE TITLE
Initial release feature checklist

### ISSUE THREAD

**Issue by mganjoo** [mganjoo/gchessboard#10]
## Input
- [x] Support touch moves
- [x] Ensure setting changes transitions out of interactive state. Additionally, ensure that all external interactions result in some form of state transition.

## Visuals
- [x] Show ghost piece while dragging piece
- [x] Customize style of ghost piece and allow disabling
- [x] Update lightness of move outline box

## Animation
- [x] Piece animation while click moving and keyboard moving
- [x] Pieces animation while changing board position
- [x] Support turning off animation manually and ensure 0ms transition period is handled correctly
- [x] Smooth animations (no flickering) when dropping

## Callbacks
- [x] Start of move, End of move

## Markers
- [x] ~Individual square markers (ensure square marking can be disabled)~
- [x] Markers for eligible move squares (returned from move start callback)
- [x] Decide style for occupied squares (with custom content) that are move-eligible (crosshairs-based markers are causing a weird overlap)
- [x] ~Arrow markers between squares~

## Visual bugs
- [x] Debug why there is a flicker when hiding/showing notation and making board interactive

## Testing
- [x] Output type declarations: https://github.com/vitejs/vite/issues/2049
- [x] Build example app that uses built version of library
- [x] Run `web-components-analyzer` to generate documentation for library

## Stretch objectives
- [x] Basic styling customization
- [x] Basic customization of animation duration
